server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sleeve?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  redis:
    host: 192.168.118.128
    port: 6379
    database: 1
    listen-pattern: '__keyevent@1__:expired'

  rocketmq:
    nameSrvAddr: 192.168.118.128:9876
    topic: sleeveSchedule
    producer:
      producerGroup: sleeveProducerScheduleGroup

    consumer:
      consumerGroup: sleeveConsumerScheduuleGroup



missyou:
  security:
    jwt-sign: chenguiquansleeveserver
    expire-time: 600
    api-scope: 4
  order:
    pay-limit-time: 60
  pay:
    notify-host: xxxxxxx
    notify-url: /v1/payment/wx/notify

